<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */

class Assetsinfo extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Assetsinfo_model');
        
    } 

    /*
     * Listing of assetsinfo
     */
    function index()
    {
        $session_data = $this->session->userdata('logged_in');
        if($this->session->userdata('logged_in') && $session_data['type']==1) 
        {    $data['type'] =$session_data['type'];
            $data['mail'] = $session_data['email'];
            $data['assetsinfo'] = $this->Assetsinfo_model->get_all_assetsinfo();
            $this->load->view('assetsinfo/assetinfo',$data);
        }
        else
        {
     //If no session, redirect to login page
         redirect('login/index', 'refresh');
     }
 }

    /*
     * Adding a new assetsinfo
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'Amount' => $this->input->post('Amount'),
                'AssetType_ID' => $this->input->post('AssetType_ID'),
                );
            
            $assetsinfo_id = $this->Assetsinfo_model->add_assetsinfo($params);
            redirect('assetsinfo/index');
        }
        else
        {
            $session_data = $this->session->userdata('logged_in');
            $data['mail'] = $session_data['email'];
            $this->load->view('assetsinfo/add',$data);
        }
    }  

    /*
     * Editing a assetsinfo
     */
    function edit($ID)
    {   
        // check if the assetsinfo exists before trying to edit it
        $assetsinfo = $this->Assetsinfo_model->get_assetsinfo($ID);
        
        if(isset($assetsinfo['ID']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                   'Amount' => $this->input->post('Amount'),
                   'AssetType_ID' => $this->input->post('AssetType_ID'),
                   );

                $this->Assetsinfo_model->update_assetsinfo($ID,$params);            
                redirect('assetsinfo/index');
            }
            else
            {   
                $data['assetsinfo'] = $this->Assetsinfo_model->get_assetsinfo($ID);
                $session_data = $this->session->userdata('logged_in');
                $data['mail'] = $session_data['email'];
                $this->load->view('assetsinfo/edit',$data);
            }
        }
        else
            show_error('The assetsinfo you are trying to edit does not exist.');
    } 

    /*
     * Deleting assetsinfo
     */
    function remove($ID)
    {
        $assetsinfo = $this->Assetsinfo_model->get_assetsinfo($ID);

        // check if the assetsinfo exists before trying to delete it
        if(isset($assetsinfo['ID']))
        {
            $this->Assetsinfo_model->delete_assetsinfo($ID);
            redirect('assetsinfo/index');
        }
        else
            show_error('The assetsinfo you are trying to delete does not exist.');
    }
    
}
