<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class Academicdetail_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get academicdetail by ID
     */
    function get_academicdetail($ID)
    {
        return $this->db->get_where('AcademicDetails',array('ID'=>$ID))->row_array();
    }
    
    /*
     * Get all academicdetails
     */
    function get_all_academicdetails()
    {  
        $query = $this->db->query("CALL displayAcademics()"); 
           return $query->result_array();
    }
    
    /*
     * function to add new academicdetail
     */
    function add_academicdetail($params)
    {
        $this->db->insert('AcademicDetails',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update academicdetail
     */
    function update_academicdetail($ID,$params)
    {
        $this->db->where('ID',$ID);
        $response = $this->db->update('AcademicDetails',$params);
        if($response)
        {
            return "academicdetail updated successfully";
        }
        else
        {
            return "Error occuring while updating academicdetail";
        }
    }
    
    /*
     * function to delete academicdetail
     */
    function delete_academicdetail($ID)
    {
        $response = $this->db->delete('AcademicDetails',array('ID'=>$ID));
        if($response)
        {
            return "academicdetail deleted successfully";
        }
        else
        {
            return "Error occuring while deleting academicdetail";
        }
    }
}
